name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"    # daily at 18:00 UTC (after your local workday)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Check if file exists
        run: |
          if [ ! -f "profile-3d-contrib.svg" ]; then
            echo "Error: profile-3d-contrib.svg not found!"
            exit 1
          fi
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib.svg
          git commit -m "chore: update 3D profile" || echo "no changes to commit"
          git push
